<?php

namespace exialps\GestionlpsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProprietaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProprietaireRepository extends EntityRepository
{
}
